kind = "web"
previewPath = "/"
title = "Sponso"
version = "1.0.0"
id = "artifacts/sponso"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25313

[services.development]
run = "pnpm --filter @workspace/sponso run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sponso", "run", "build" ]
publicDir = "artifacts/sponso/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25313"
BASE_PATH = "/"
